name: Update every 2 hours

on:
  push:
      branches:
        - master
  schedule:
  - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: setup git config
        run: |
         git config user.name ${{ secrets.USERNAME }}
         git config user.email ${{ secrets.EMAIL }}
#       - name: checkout to fetch_data branch
#         run: |
#          chmod +x ./scripts/switch_branch.sh
#          ./scripts/switch_branch.sh
      - name: checkout to fetch_data branch
        uses: actions/checkout@v2
        with:
          ref: fetch_data
      - name: execute py script # run the run.py to get the latest data
        run: |
          python main.py
        env: 
          key: ${{ secrets.KEY }}
          secret: ${{ secrets.SECRET }}
      
      - name: commit changes
        run: |
         chmod +x ./scripts/commit.sh
         ./scripts/commit.sh

